# Generated by Django 3.2.6 on 2021-11-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211119_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
