# Generated by Django 3.2.6 on 2021-11-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_tmdb_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
